### ISSUE TITLE
Math::Int128 still required for install

### ISSUE THREAD

**Issue by vsespb** [maxmind/MaxMind-DB-Reader-perl#23]
This PR removed Math::Int128 dependency
https://github.com/maxmind/MaxMind-DB-Reader-perl/pull/17

However, I see it's still in cpanfile in "on-test" section.

on 32bit machine:

```
# cpanm GeoIP2
--> Working on GeoIP2
Fetching http://search.cpan.org/CPAN/authors/id/M/MA/MAXMIND/GeoIP2-2.001003.tar.gz ... OK
Configuring GeoIP2-2.001003 ... OK
==> Found dependencies: MaxMind::DB::Reader
--> Working on MaxMind::DB::Reader
Fetching http://search.cpan.org/CPAN/authors/id/M/MA/MAXMIND/MaxMind-DB-Reader-1.000007.tar.gz ... OK
Configuring MaxMind-DB-Reader-1.000007 ... OK
==> Found dependencies: Net::Works::Network, Math::Int128
--> Working on Net::Works::Network
Fetching http://search.cpan.org/CPAN/authors/id/M/MA/MAXMIND/Net-Works-0.21.tar.gz ... OK
Configuring Net-Works-0.21 ... OK
==> Found dependencies: Math::Int128
--> Working on Math::Int128
Fetching http://search.cpan.org/CPAN/authors/id/S/SA/SALVA/Math-Int128-0.22.tar.gz ... OK
Configuring Math-Int128-0.22 ... N/A
! Configure failed for Math-Int128-0.22. See /root/.cpanm/build.log for details.
! Bailing out the installation for Net-Works-0.21. Retry with --prompt or --force.
! Bailing out the installation for MaxMind-DB-Reader-1.000007. Retry with --prompt or --force.
! Bailing out the installation for GeoIP2-2.001003. Retry with --prompt or --force.
```

**Comment by autarch** [comment]
There was still some test code using it. I've fixed this in the repo and I think we can do a new release shortly.

**Comment by vsespb** [comment]
thx!

**Comment by autarch** [comment]
Fixed in https://metacpan.org/release/MAXMIND/MaxMind-DB-Reader-1.000008

Cheers,

-dave

**Comment by vsespb** [comment]
Still does not work:
```
# cpanm --force MaxMind::DB::Reader
--> Working on MaxMind::DB::Reader
Fetching http://search.cpan.org/CPAN/authors/id/M/MA/MAXMIND/MaxMind-DB-Reader-1.000008.tar.gz ... OK
Configuring MaxMind-DB-Reader-1.000008 ... OK
==> Found dependencies: Net::Works::Network
--> Working on Net::Works::Network
Fetching http://search.cpan.org/CPAN/authors/id/M/MA/MAXMIND/Net-Works-0.21.tar.gz ... OK
Configuring Net-Works-0.21 ... OK
==> Found dependencies: Math::Int128
--> Working on Math::Int128
Fetching http://search.cpan.org/CPAN/authors/id/S/SA/SALVA/Math-Int128-0.22.tar.gz ... OK
Configuring Math-Int128-0.22 ... N/A
! Configure failed for Math-Int128-0.22. See /root/.cpanm/build.log for details.
! Bailing out the installation for Net-Works-0.21. Retry with --prompt or --force.
! Bailing out the installation for MaxMind-DB-Reader-1.000008. Retry with --prompt or --force.
```

I think problem is  :
```
build_requires:
  Exporter: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Net::Works::Network: '0.21'
```

and Net::Works requires Math::Int128

**Comment by oschwald** [comment]
You are right. The `Net::Works` test dependency should be made optional as well.

**Comment by autarch** [comment]
Ok, I think this is really finally fixed in https://metacpan.org/release/MAXMIND/MaxMind-DB-Reader-1.000009

**Comment by vsespb** [comment]
seems it finaly works. thanks

```
# cpanm  MaxMind::DB::Reader
--> Working on MaxMind::DB::Reader
Fetching http://search.cpan.org/CPAN/authors/id/M/MA/MAXMIND/MaxMind-DB-Reader-1.000009.tar.gz ... OK
Configuring MaxMind-DB-Reader-1.000009 ... OK
Building and testing MaxMind-DB-Reader-1.000009 ... OK
Successfully installed MaxMind-DB-Reader-1.000009 (upgraded from 1.000008)
1 distribution installed
```

**Comment by autarch** [comment]
Huzzah!
